// GENERATED by tools/build_web.py from src/blendboxd/output.py (the viewer the
// Python app renders). Do not edit: change the template and rebuild.
export function startViewer(boot) {
const NAMES = boot.names;
// Which members' chips load ON by default (parallel to NAMES): the owner loads ON,
// friends OFF (the renderer decides) — so a group starts on the owner's taste and
// opts friends in via the chips. All-true (the default) reproduces the old
// everyone-selected behavior. See blendboxd.friends.
const MEMBER_ACTIVE = boot.memberActive;
function initialMembers(){
  // Member indices whose chip loads ON. Guard: never open on an empty blend (which
  // would score every film 0) — if nobody is active by default, fall back to all.
  const on = NAMES.map((_,i)=>i).filter(i => MEMBER_ACTIVE[i]);
  return on.length ? on : NAMES.map((_,i)=>i);
}
const MAX_SHOW = boot.maxShow;
const LIVE = boot.live;
const POLL_URL = boot.pollUrl;
const COMBINER = boot.combiner;  // blend method; must match score.py's combine()
const HAS_CINE = boot.hasCine;  // is the cineblend tab present?
// Cinemas behind the cineblend pool: [{id,name,logo}, …].
// Each cine film carries a `cinemas` list of the venue id(s) showing it; the
// cinema filter (cine tab only) and the per-card logos read these.
const CINEMAS = boot.cinemas;
const CINEMA_BY_ID = Object.fromEntries(CINEMAS.map(c => [c.id, c]));
// Cinemas that failed to load (unreachable/blocked/none-matched) — surfaced on the
// cineblend tab so a failure is never silent. A cinema with nothing showing is not
// listed here (it just doesn't appear).
const CINEMA_ISSUES = boot.cinemaIssues;
// Two pools behind the top-bar tabs: "blend" (full TMDb catalogue) and "cine"
// (films now showing locally). They share the members / combiner / controls; only
// the candidate pool differs. DATA points at the active tab's pool; switchTab()
// repoints it and rebuilds the facet chips.
const DATASETS = {
  blend: boot.data,
  cine:  boot.dataCine,
};
const SUBTITLES = { blend: boot.subtitleBlend, cine: boot.subtitleCine };
let ACTIVE = 'blend';
let DATA = DATASETS.blend;
// Per-profile bar colors. 1-2 members keep the familiar orange/green; a larger
// group gets an evenly-spaced HSL ramp. Kept separate from the driver-tag colors
// (--group/--personal), which still legend genre/keyword/director.
function profilePalette(n){
  if(n <= 2) return ['var(--group)', 'var(--personal)'].slice(0, Math.max(1, n));
  return Array.from({length:n}, (_,i) => `hsl(${Math.round(360*i/n)} 68% 55%)`);
}
const PROFILE_COLORS = profilePalette(NAMES.length);
// SOLO = only one member exists at all (governs load-time UI like the sort menu).
// soloView() below is the *live* "only one member currently selected" check.
const SOLO = NAMES.length === 1;
// Vibe presets: each sets the three signed axis weights.
const VIBE_PRESETS = {
  wiped:     {len:-0.8, cx:-0.8, en: 0.0},  // 😴 penalize long + complex
  easy:      {len:-0.3, cx:-0.7, en: 0.7},  // 🍿 simple + energetic, slightly shorter
  slow:      {len: 0.3, cx: 0.8, en:-0.6},  // 🌙 favor slow arthouse, length-tolerant, calm
  challenge: {len: 0.7, cx: 0.9, en: 0.0},  // ⚡ up for long + demanding
};
let maxCombined = 0.0001;
let MOOD_ON = false;    // set per-render: true when the vibe re-ranks the combined sort
let FRESH = new Set();  // tmdb_urls new since the last live update; briefly highlighted
const state = { q:'', sort:'combined', dir:-1, rmin:null, rmax:null, minr:null,
                ymin:null, ymax:null, watched:'hide',
                gmode:'or', genres:new Set(), countries:new Set(), decades:new Set(),
                members:new Set(initialMembers()),  // in the blend at load (owner on, friends off)
                cinemas:new Set(CINEMAS.map(c=>c.id)),  // cineblend: which venues to show (all)
                vibe:{len:0, cx:0, en:0, beta:0.5, preset:null} };

// ---- client-side re-blend: toggling members re-combines the already-embedded
// per-member scores, live, with no pipeline re-run. combineScores() mirrors
// score.py's combine() exactly (soft floor 0.02, n=1 identity, same folds), so
// selecting everyone reproduces the server's combined_score bit-for-bit.
const EPS_COMBINE = 0.02;
function combineScores(scores, method){
  const n = scores.length;
  if(n === 0) return 0;
  if(n === 1) return scores[0];                     // identity (solo), no flooring
  const s = scores.map(x => Math.max(x, EPS_COMBINE));
  if(method === 'min') return Math.min(...s);
  if(method === 'geometric') return Math.pow(s.reduce((a,b)=>a*b, 1), 1/n);
  return n / s.reduce((a,b)=>a + 1/b, 0);           // harmonic (default)
}
const selIdx = () => [...state.members].sort((a,b)=>a-b);      // selected member indices
const soloView = () => state.members.size === 1;              // only one member selected now
function blendOf(d){                                          // the blend over selected members
  // Everyone selected -> use the server's full-precision combined_score verbatim
  // (the embedded per-member scores are rounded, so recombining them would drift
  // ~1e-4 and could reorder near-ties). Only an actual toggle re-blends client-side.
  if(state.members.size === NAMES.length) return d.combined || 0;
  return combineScores(selIdx().map(i => (d.scores||[])[i] || 0), COMBINER);
}
let SELSET = new Set(NAMES);                                  // selected member NAMES (for watched)
function syncSel(){ SELSET = new Set(selIdx().map(i => NAMES[i])); }
// A film counts as "seen" only if a *selected* member has watched it — deselecting
// a member brings back the films only they had seen.
const isSeen = d => (d.watched_by||[]).some(n => SELSET.has(n));
function recomputeMax(){ maxCombined = Math.max(0.0001, ...DATA.map(d => blendOf(d))); }
recomputeMax();

// Shared taste drivers for the CURRENT member selection. Everyone selected -> the
// server's full-group top-3 (features): exact and zero-cost. A subset -> recompute
// from the per-member contributions (dcon): a token drives the blend only if every
// selected member is pulled toward it, so rank tokens by the MIN contribution over
// the selected members, keep the positives, take the top 3 (mirrors score.py's
// taste_drivers / driver_contributions).
const DRIVER_LIMIT = 3;
function driversFor(d){
  if(state.members.size === NAMES.length) return d.features || [];
  const idx = selIdx(), ranked = [];
  for(const t of (d.dcon || [])){
    let m = Infinity;
    for(const i of idx) m = Math.min(m, (t.c||[])[i] || 0);
    if(m > 0) ranked.push({drive:m, cat:t.cat, name:t.name});
  }
  ranked.sort((a,b) => b.drive - a.drive);
  return ranked.slice(0, DRIVER_LIMIT).map(r => ({cat:r.cat, name:r.name}));
}

const el = id => document.getElementById(id);
const uniq = key => [...new Set(DATA.flatMap(d => d[key] || []))].sort((a,b)=>a.localeCompare(b));
// Distinct decades present in the pool (e.g. 1950, 1960, …), ascending.
const decadeValues = () => [...new Set(DATA.filter(d => d.year!=null)
  .map(d => Math.floor(d.year/10)*10))].sort((a,b)=>a-b);

function chipRow(container, values, setRef, label){
  // Do NOT prune selected values that are absent from this pool. The blendboxd and
  // cineblend tabs share these filter Sets, and the cine pool is a much narrower
  // facet universe, so pruning here would silently drop a selection (e.g. a genre
  // chosen on blendboxd) the moment the user peeks at cineblend, never to return.
  // An absent value simply renders no chip on this tab; it stays in the Set and
  // keeps filtering, and its chip reappears when the pool contains it again. (Live
  // widening only ever grows the pool, so nothing is legitimately pruned anyway.)
  const lbl = label || (v => v);
  container.innerHTML = '';
  for(const v of values){
    const c = document.createElement('span');
    c.className = 'chip'; c.textContent = lbl(v);
    if(setRef.has(v)) c.classList.add('on');
    c.onclick = () => { setRef.has(v) ? setRef.delete(v) : setRef.add(v);
      c.classList.toggle('on'); render(); };
    container.appendChild(c);
  }
}

function passes(d){
  // Watched view mode: hide = only recs; only = only seen; dim = show both.
  if(state.watched === 'hide' && isSeen(d)) return false;
  if(state.watched === 'only' && !isSeen(d)) return false;
  if(state.q){
    const hay = (d.title + ' ' + (d.directors||[]).join(' ')).toLowerCase();
    if(!hay.includes(state.q)) return false;
  }
  if(state.genres.size){
    const g = d.genres || [];
    const ok = state.gmode === 'and'
      ? [...state.genres].every(x => g.includes(x))   // AND: film has every selected genre
      : g.some(x => state.genres.has(x));              // OR: film has any selected genre
    if(!ok) return false;
  }
  if(state.countries.size && !(d.countries||[]).some(c => state.countries.has(c))) return false;
  // Cinema filter (cineblend only): a film passes if any selected venue shows it.
  // All venues selected (the default) is a no-op, matching the other facet chips.
  if(ACTIVE==='cine' && CINEMAS.length && state.cinemas.size < CINEMAS.length){
    if(!(d.cinemas||[]).some(c => state.cinemas.has(c))) return false;
  }
  if(state.minr != null && (d.tmdb_rating||0) < state.minr) return false;
  if(state.rmin != null){ if(d.runtime == null || d.runtime < state.rmin) return false; }
  if(state.rmax != null){ if(d.runtime == null || d.runtime > state.rmax) return false; }
  // Year/decade filters exclude films with no year (mirrors the runtime filter).
  if(state.decades.size){
    if(d.year == null || !state.decades.has(Math.floor(d.year/10)*10)) return false;
  }
  if(state.ymin != null){ if(d.year == null || d.year < state.ymin) return false; }
  if(state.ymax != null){ if(d.year == null || d.year > state.ymax) return false; }
  return true;
}

function esc(s){ return (s==null?'':String(s)).replace(/[&<>"]/g, c =>
  ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }

function card(d){
  const initial = esc((d.title||'?')[0]);
  const poster = d.poster
    ? `<img loading="lazy" src="${esc(d.poster)}" alt="${esc(d.title)} poster" data-ph="${initial}"
         onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'ph',textContent:this.dataset.ph}))">`
    : `<div class="ph">${initial}</div>`;
  // Show ALL genres (no truncation) and highlight the ones being filtered on,
  // so an AND match is visibly correct even when a film has 5-6 genres.
  const genres = (d.genres||[]).map(g=>
    `<span${state.genres.has(g)?' class="sel"':''}>${esc(g)}</span>`).join('');
  const meta = [ esc((d.countries||[]).join(', ')), d.runtime ? d.runtime+' min' : '' ]
    .filter(Boolean).join(' &middot; ');
  // Per-card cinema marks: show which venue(s) play each film whenever the pool
  // has more than one cinema — a film playing at several shows ALL their logos.
  // (Redundant, so hidden, when the pool is a single cinema: every card is from it.)
  const showLogos = ACTIVE==='cine' && CINEMAS.length > 1;
  const cinelogos = (showLogos && (d.cinemas||[]).length)
    ? `<div class="cinelogos">${(d.cinemas||[]).map(id=>{
        const c = CINEMA_BY_ID[id]; if(!c) return '';
        return `<img loading="lazy" src="${esc(c.logo)}" title="${esc(c.name)}" alt="${esc(c.name)}">`;
      }).join('')}</div>`
    : '';
  const bar = (lbl,val,color)=>{
    const w = Math.max(2, Math.round((val/maxCombined)*100));
    const shown = lbl.length>8 ? lbl.slice(0,7)+'…' : lbl;
    return `<div class="bar"><span class="lbl" title="${esc(lbl)}">${esc(shown)}</span>
      <span class="track"><span class="fill" style="width:${w}%;background:${color}"></span></span>
      <span class="val">${val.toFixed(2)}</span></div>`;
  };
  // Per-member bars: only the selected members, in a stable order. With one member
  // selected there are no per-member bars (the blend bar below is their score).
  const idx = selIdx();
  const scoreBars = soloView() ? '' : idx.map(i =>
    bar(NAMES[i], (d.scores||[])[i]||0, PROFILE_COLORS[i%PROFILE_COLORS.length])).join('');
  const seen = isSeen(d);
  // Rank badge: taste rank #N over the current member selection, and under an active
  // vibe also the mood rank -> "#N → #N'". Seen (by a selected member) -> no rank.
  const tr = d._trank;
  const badge = tr==null ? ''
    : (MOOD_ON && d._mrank)
      ? `<span class="rankbadge">#${tr}<span class="arrow">→</span>#${d._mrank}</span>`
      : `<span class="rankbadge">#${tr}</span>`;
  // Taste drivers (#4a): the shared features that lifted the blend score, for the
  // current member selection (recomputed per subset from dcon — see driversFor).
  const drv = driversFor(d);
  const drivers = drv.length
    ? `<div class="drivers"><span class="dl">${soloView() ? 'Top' : 'Shared'}</span>${drv.map(f=>
        `<span class="dtag ${esc(f.cat)}">${esc(f.name)}</span>`).join('')}</div>`
    : '';
  // Mood readout (#4b): S -> S' with delta + each steered axis's signed push.
  let moodx = '';
  if(MOOD_ON){
    const mb = moodBreakdown(d);
    const dcls = mb.delta > 0.0005 ? 'up' : (mb.delta < -0.0005 ? 'down' : '');
    const axp = mb.axes.map(a => `<span>${a.label}<b>${fmtSigned(a.contrib)}</b></span>`).join('');
    moodx = `<div class="moodx">
      <div class="mrow">blend <b>${mb.S.toFixed(2)}</b><span class="arrow">→</span><b>${mb.Sp.toFixed(2)}</b>
        <span class="delta ${dcls}">${fmtSigned(mb.delta)}</span></div>
      ${axp ? `<div class="axpush">${axp}</div>` : ''}</div>`;
  }
  return `<article class="card${seen?' seen':''}${FRESH.has(d.tmdb_url)?' fresh':''}">
    <div class="poster">${badge}
      <span class="rate">★ ${(d.tmdb_rating||0).toFixed(1)}</span>${poster}</div>
    <div class="body">
      <div class="title"><a href="${esc(d.tmdb_url)}" target="_blank" rel="noopener">
        ${esc(d.title)}</a> <span class="yr">${d.year||''}</span></div>
      <div class="dir">${esc((d.directors||[]).join('; ')) || '—'}</div>
      ${seen?`<div class="seenby">✓ Seen by ${esc((d.watched_by||[]).filter(n=>SELSET.has(n)).join(', '))}</div>`:''}
      <div class="gchips">${genres}</div>
      ${drivers}
      ${meta ? `<div class="meta">${meta}</div>` : ''}
      <div class="cardfoot">
        ${cinelogos}
        <div class="scores">
          ${scoreBars}
          ${bar(soloView() ? NAMES[idx[0]] : 'blend', blendOf(d), 'var(--combined)')}
          ${moodx}
        </div>
      </div>
    </div></article>`;
}

function sortValue(d, k){
  if(k === 'combined') return blendOf(d);            // the blend over selected members
  if(k.startsWith('score')) return (d.scores||[])[+k.slice(5)];
  return d[k];
}

// ---- mood-aware re-rank: a taste-preserving layer on top of the combined score.
// Axis loads are absolute in [0,1] (0.5 = neutral); center them, take the weighted
// average A in [-1,+1], then S' = S * (1 + beta * A). Missing/neutral axes -> 0.
function moodCenter(load){ return load==null ? 0 : 2*load - 1; }
function moodActive(){ const v=state.vibe; return (Math.abs(v.len)+Math.abs(v.cx)+Math.abs(v.en))>0; }
function moodAdjusted(d){
  const v = state.vibe;
  const den = Math.abs(v.len)+Math.abs(v.cx)+Math.abs(v.en);
  const S = blendOf(d);                          // taste score = the current-selection blend
  if(den === 0) return S;                       // all sliders neutral -> taste order unchanged
  const ax = d.axes || {};
  const A = ( v.len*moodCenter(ax.length)
            + v.cx *moodCenter(ax.complexity)
            + v.en *moodCenter(ax.energy) ) / den;   // weighted avg, bounded [-1,+1]
  return S * (1 + v.beta * A);                  // multiplicative, keeps taste dominant
}
// Per-card mood breakdown for the explainability readout (#4b): the taste score S,
// the re-ranked S', their delta, and each steered axis's signed contribution to A
// (the parts sum to A, so S' = S*(1+beta*A)). Axes the user isn't steering are hidden.
const AXIS_META = [
  {k:'len', key:'length',     label:'Length'},
  {k:'cx',  key:'complexity', label:'Complexity'},
  {k:'en',  key:'energy',     label:'Energy'},
];
function moodBreakdown(d){
  const v = state.vibe;
  const den = Math.abs(v.len)+Math.abs(v.cx)+Math.abs(v.en);
  const S = blendOf(d);                          // taste score = the current-selection blend
  if(den === 0) return {S, Sp:S, delta:0, axes:[]};
  const ax = d.axes || {};
  let A = 0; const parts = [];
  for(const m of AXIS_META){
    const contrib = (v[m.k] * moodCenter(ax[m.key])) / den;  // signed; the parts sum to A
    A += contrib;
    if(v[m.k] !== 0) parts.push({label:m.label, contrib});
  }
  const Sp = S * (1 + v.beta * A);
  return {S, Sp, delta: Sp - S, axes: parts};
}
function fmtSigned(x){ return Math.abs(x) < 0.005 ? '0' : (x>0?'+':'−') + Math.abs(x).toFixed(2); }

function render(){
  const k = state.sort;
  // Global taste rank #N over the current recommendation pool (films no *selected*
  // member has seen), by the current-selection blend — recomputed here so it tracks
  // member toggles. Seen films get no rank. It's global (not filter-scoped) so the
  // "#N" badge is stable as you filter.
  const recs = DATA.filter(d => !isSeen(d));
  recs.slice().sort((a,b) => blendOf(b) - blendOf(a)).forEach((d,i) => d._trank = i+1);
  DATA.forEach(d => { if(isSeen(d)) d._trank = null; });
  // Mood only re-orders the taste ranking, so it applies when sorting by combined score.
  const useMood = (k==='combined') && moodActive();
  MOOD_ON = useMood;
  if(useMood){
    // Global mood rank (N') over the same recommendation pool, so the "#N → #N'"
    // badge is filter-independent — it matches the taste rank N, which is also global.
    recs.slice().sort((a,b) => moodAdjusted(b) - moodAdjusted(a))
      .forEach((d,i) => d._mrank = i+1);
  } else {
    DATA.forEach(d => d._mrank = null);
  }
  let rows = DATA.filter(passes);
  rows.sort((a,b)=>{
    if(k==='title'){ return state.dir * String(a.title).localeCompare(String(b.title)); }
    let av = useMood ? moodAdjusted(a) : sortValue(a,k);
    let bv = useMood ? moodAdjusted(b) : sortValue(b,k);
    av = av==null?-Infinity:av; bv = bv==null?-Infinity:bv;
    return state.dir * (av<bv?-1:av>bv?1:0);
  });
  const matches = rows.length;
  const shown = rows.slice(0, MAX_SHOW);   // draw up to MAX_SHOW from the whole pool
  el('grid').innerHTML = shown.map(card).join('');
  el('empty').hidden = matches>0;
  const vs = el('vibeState'); if(vs) vs.textContent = moodActive() ? ' · on' : '';
  const capped = matches > MAX_SHOW ? ` (top ${MAX_SHOW} shown)` : '';
  const moodNote = useMood ? ' · vibe re-ranked' : '';
  const memNote = (state.members.size < NAMES.length)
    ? ` · blending ${state.members.size}/${NAMES.length} members` : '';
  el('count').textContent = `${matches} match${matches===1?'':'es'} of ${DATA.length} scored${capped}${memNote}${moodNote}`;
}

el('q').oninput = e => { state.q = e.target.value.trim().toLowerCase(); render(); };
el('sort').onchange = e => { state.sort = e.target.value;
  state.dir = (e.target.value==='title') ? 1 : -1; updateDirBtn(); render(); };
el('dir').onclick = () => { state.dir *= -1; updateDirBtn(); render(); };
el('rmin').oninput = e => { state.rmin = e.target.value===''?null:+e.target.value; render(); };
el('rmax').oninput = e => { state.rmax = e.target.value===''?null:+e.target.value; render(); };
el('ymin').oninput = e => { state.ymin = e.target.value===''?null:+e.target.value; render(); };
el('ymax').oninput = e => { state.ymax = e.target.value===''?null:+e.target.value; render(); };
el('minr').oninput = e => { state.minr = e.target.value===''?null:+e.target.value; render(); };
el('reset').onclick = () => {
  state.q=''; state.rmin=state.rmax=state.minr=null; state.ymin=state.ymax=null;
  state.watched='hide';
  state.gmode='or'; state.genres.clear(); state.countries.clear(); state.decades.clear();
  el('q').value=''; el('rmin').value=el('rmax').value=el('minr').value='';
  el('ymin').value=el('ymax').value='';
  document.querySelectorAll('.chip.on').forEach(c=>c.classList.remove('on'));
  document.querySelectorAll('#gmode .gm').forEach(b=>b.classList.toggle('on', b.dataset.mode==='or'));
  document.querySelectorAll('#wmode .sg').forEach(b=>b.classList.toggle('on', b.dataset.w==='hide'));
  state.vibe.len=state.vibe.cx=state.vibe.en=0; state.vibe.beta=0.5;
  setPreset(null); syncVibeSliders(); syncVibeOutputs();
  state.members = new Set(NAMES.map((_,i)=>i));  // all members back in the blend
  syncSel(); recomputeMax(); renderMembers();
  state.cinemas = new Set(CINEMAS.map(c=>c.id));  // all venues back on (cineblend)
  renderCinemas();
  render();
};
// Members: toggle who is in the blend. At least one must stay selected. Deselecting
// re-blends live from the embedded per-member scores (no pipeline re-run) and un-hides
// films only a deselected member had watched.
function renderMembers(){
  const box = el('members'); if(!box) return;
  box.innerHTML = '';
  NAMES.forEach((n,i) => {
    const on = state.members.has(i);
    const c = document.createElement('span');
    c.className = 'chip member' + (on ? '' : ' off');
    c.innerHTML = `<span class="swatch" style="background:${PROFILE_COLORS[i%PROFILE_COLORS.length]}"></span>${esc(n)}`;
    c.title = on ? `${n} is in the blend — click to drop` : `${n} is out — click to add`;
    c.onclick = () => {
      if(state.members.has(i)){
        if(state.members.size <= 1) return;   // keep at least one member in the blend
        state.members.delete(i);
      } else state.members.add(i);
      syncSel(); recomputeMax(); renderMembers(); render();
    };
    box.appendChild(c);
  });
}
// Cineblend cinema filter: toggle which venues' films show. Chips carry a small
// logo + name; deselecting hides that cinema's films (a film shared by several
// stays while any of them is on). Built once (the venue set is fixed at load).
function renderCinemas(){
  const box = el('cinemas'); if(!box) return;
  box.innerHTML = '';
  CINEMAS.forEach(c => {
    const on = state.cinemas.has(c.id);
    const chip = document.createElement('span');
    chip.className = 'chip cinema' + (on ? ' on' : ' off');
    chip.innerHTML = `<img class="clogo" src="${esc(c.logo)}" alt="">${esc(c.name)}`;
    chip.title = on ? `${c.name} shown — click to hide its films`
                    : `${c.name} hidden — click to show its films`;
    chip.onclick = () => {
      state.cinemas.has(c.id) ? state.cinemas.delete(c.id) : state.cinemas.add(c.id);
      renderCinemas(); render();
    };
    box.appendChild(chip);
  });
}
// Genre match mode: OR (any selected) | AND (all selected).
document.querySelectorAll('#gmode .gm').forEach(b => b.onclick = () => {
  state.gmode = b.dataset.mode;
  document.querySelectorAll('#gmode .gm').forEach(x => x.classList.toggle('on', x.dataset.mode===state.gmode));
  render();
});
// Watched view mode: Hide (recs only) | Dim (show seen, dimmed) | Only (seen only).
document.querySelectorAll('#wmode .sg').forEach(b => b.onclick = () => {
  state.watched = b.dataset.w;
  document.querySelectorAll('#wmode .sg').forEach(x => x.classList.toggle('on', x.dataset.w===state.watched));
  render();
});

// ---------------------------------------------------------------- Vibe panel
function syncVibeOutputs(){
  el('v_len_v').textContent  = state.vibe.len.toFixed(2);
  el('v_cx_v').textContent   = state.vibe.cx.toFixed(2);
  el('v_en_v').textContent   = state.vibe.en.toFixed(2);
  el('v_beta_v').textContent = state.vibe.beta.toFixed(2);
}
function setPreset(name){
  state.vibe.preset = name;
  document.querySelectorAll('#presets .preset').forEach(b =>
    b.classList.toggle('on', b.dataset.preset===name));
}
function syncVibeSliders(){
  el('v_len').value = state.vibe.len; el('v_cx').value = state.vibe.cx;
  el('v_en').value = state.vibe.en;   el('v_beta').value = state.vibe.beta;
}
const snapDetent = v => Math.abs(v) < 0.08 ? 0 : v;  // center detent on the signed sliders
[['len','v_len'],['cx','v_cx'],['en','v_en']].forEach(([ax,id]) => {
  el(id).oninput = e => {
    const val = snapDetent(+e.target.value);
    if(val === 0) e.target.value = 0;     // visually snap to center
    state.vibe[ax] = val;
    setPreset(null);                       // dragging any slider clears the active preset
    syncVibeOutputs(); render();
  };
});
el('v_beta').oninput = e => { state.vibe.beta = +e.target.value; syncVibeOutputs(); render(); };
document.querySelectorAll('#presets .preset').forEach(b => b.onclick = () => {
  const p = VIBE_PRESETS[b.dataset.preset];
  if(!p) return;
  if(state.vibe.preset === b.dataset.preset){          // click active preset again -> clear axes
    state.vibe.len = state.vibe.cx = state.vibe.en = 0; setPreset(null);
  } else {
    state.vibe.len = p.len; state.vibe.cx = p.cx; state.vibe.en = p.en; setPreset(b.dataset.preset);
  }
  syncVibeSliders(); syncVibeOutputs(); render();
});
syncVibeOutputs();

function updateDirBtn(){ el('dir').textContent = state.dir<0 ? '▼ desc' : '▲ asc'; }

// Inject one sort option per profile (after "Combined score"). Skipped when solo
// — the single per-profile score is the combined score, so it'd just duplicate.
const sortSel = el('sort');
if(!SOLO) NAMES.forEach((n, i) => {
  const o = document.createElement('option');
  o.value = 'score' + i; o.textContent = n + ' score';
  sortSel.insertBefore(o, sortSel.children[1 + i]);
});

// Members bar: only shown when there's more than one member to toggle.
if(NAMES.length > 1){ el('memberbar').hidden = false; syncSel(); renderMembers(); }
// Cinema chips are built once (fixed venue set); the bar shows only on cineblend.
if(CINEMAS.length){ renderCinemas(); }
chipRow(el('genres'), uniq('genres'), state.genres);
chipRow(el('countries'), uniq('countries'), state.countries);
chipRow(el('decades'), decadeValues(), state.decades, v => v + 's');
updateDirBtn();
render();

// ---------------------------------------- top-bar tabs (blendboxd / cineblend)
// The two tabs share every control (members, vibe, filters, sort); only the
// candidate pool differs. Switching repoints DATA at the tab's pool and rebuilds
// the facet chips, preserving filter/sort/member/vibe state.
document.querySelectorAll('#tabs .tab').forEach(b => b.onclick = () => switchTab(b.dataset.tab));
function applyTabChrome(){
  el('sub').innerHTML = SUBTITLES[ACTIVE] || '';
  document.querySelectorAll('#tabs .tab').forEach(b => b.classList.toggle('on', b.dataset.tab===ACTIVE));
  // The cinema filter + load-failure notice only make sense on cineblend.
  const cb = el('cinemabar'); if(cb) cb.hidden = !(ACTIVE==='cine' && CINEMAS.length>0);
  renderCineNotice();
}
// Surface any cinema that failed to load (cineblend tab only). Elegant failure:
// the user is told, the rest of the pool still works, nothing crashes.
function renderCineNotice(){
  const box = el('cinenotice'); if(!box) return;
  const show = ACTIVE==='cine' && CINEMA_ISSUES.length > 0;
  box.hidden = !show;
  if(show){
    box.innerHTML = '<span class="warn">&#9888; Some cinemas couldn\'t be loaded:</span>'
      + CINEMA_ISSUES.map(m => `<span class="item">${esc(m)}</span>`).join('');
  }
}
function rebuildFacets(){
  recomputeMax();
  chipRow(el('genres'), uniq('genres'), state.genres);
  chipRow(el('countries'), uniq('countries'), state.countries);
  chipRow(el('decades'), decadeValues(), state.decades, v => v + 's');
}
function switchTab(tab){
  if(tab === ACTIVE || !DATASETS[tab]) return;
  ACTIVE = tab; DATA = DATASETS[tab]; FRESH = new Set();
  applyTabChrome(); rebuildFacets();
  prevIds = new Set(DATA.map(d => d.tmdb_url));
  prevTop = topSignature(DATA);
  render(); updateStatus();
  // The poll now targets the newly active tab, so the server deepens the tab we're
  // viewing (and pauses the other). Restart it if anything is still deepening.
  if(LIVE && POLL_URL){ ensureTimer(); poll(); }
}
applyTabChrome();

// ------------------------------------------------------------- live deepening
// In live mode the page polls POLL_URL for a fresher (wider) ranked pool for the
// ACTIVE tab and re-renders in place, keeping the user's search / filters / sort.
// The active tab is sent so the server focuses deepening on the tab we're viewing.
function setStatus(text, cls){
  const s = el('status'); if(!s) return;
  s.hidden = false; s.className = 'status ' + (cls||'');
  el('statustext').textContent = text;
}
function topSignature(data){
  // Identity of the current top MAX_SHOW by the server's ranking (combined desc).
  return data.slice(0, MAX_SHOW).map(d => d.tmdb_url).join('|');
}
let prevTop = topSignature(DATA);
let prevIds = new Set(DATA.map(d => d.tmdb_url));

function applyUpdate(films){
  FRESH = new Set(films.filter(d => !prevIds.has(d.tmdb_url)).map(d => d.tmdb_url));
  DATA = films;
  rebuildFacets();
  render();
  prevIds = new Set(DATA.map(d => d.tmdb_url));
  // Clear the highlight set shortly after so later (user-triggered) renders don't reflash.
  setTimeout(() => { FRESH = new Set(); }, 1400);
}

// Per-tab live bookkeeping. The blend pool deepens; the cine pool is fixed (done
// at load) so it never streams updates — polling it only reports the active tab so
// the server pauses blend deepening while we're on cineblend.
const GEN = { blend: -1, cine: 0 };
const DONE = { blend: !LIVE, cine: true };
const allDone = () => DONE.blend && (!HAS_CINE || DONE.cine);
function updateStatus(s){
  if(!LIVE) return;                               // static file shows no status line
  const n = DATA.length;
  if(ACTIVE === 'cine'){ setStatus(`Now showing — ${n} films`, 'done'); return; }
  const pass = s && s.pass ? ` pass ${s.pass} ·` : '';
  setStatus(DONE.blend ? `Search complete — ${n} films` : `Deepening…${pass} ${n} films`,
            DONE.blend ? 'done' : 'searching');
}

// Where live updates come from: the local server's POLL_URL (Python --serve), or an
// in-page source when the host page provides window.blendboxdState(tab, since) —
// the browser app runs the engine itself and answers with the same payload shape.
async function fetchState(tab, since){
  if(typeof window.blendboxdState === 'function') return window.blendboxdState(tab, since);
  const sep = POLL_URL.includes('?') ? '&' : '?';
  const r = await fetch(`${POLL_URL}${sep}tab=${tab}&since=${since}`, {cache:'no-store'});
  return r.ok ? r.json() : null;
}

async function poll(){
  try{
    const tab = ACTIVE;
    const s = await fetchState(tab, GEN[tab]);
    if(!s) return;
    const t = s.tab || tab;
    if(typeof s.done === 'boolean') DONE[t] = s.done;
    if(s.generation !== GEN[t] && Array.isArray(s.films)){
      GEN[t] = s.generation;
      DATASETS[t] = s.films;
      if(t === ACTIVE){ applyUpdate(s.films); prevTop = topSignature(DATA); }
    } else if(typeof s.generation === 'number'){
      GEN[t] = s.generation;
    }
    if(t === ACTIVE) updateStatus(s);
    if(allDone() && timer){ clearInterval(timer); timer = null; }
  }catch(e){ /* transient: server not ready or shutting down */ }
}

let timer = null;
function ensureTimer(){ if(LIVE && POLL_URL && !timer && !allDone()) timer = setInterval(poll, 3000); }
if(LIVE && POLL_URL){
  setStatus('Deepening…', 'searching');
  poll();
  ensureTimer();
}
}
